name: Lint Dockerfile
on: pull_request # defaults to types: [opened, synchronize, reopened]
jobs:
  dockerfilelint:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hadolint/hadolint
      IMAGE_TAG: v2.9.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files 
        uses: tj-actions/changed-files@v26.1

      - name: Lint Dockerfile if changed
        run: |
          if grep -E "Dockerfile" <<<"${{ steps.changed-files.outputs.all_changed_files }}" >/dev/null; then
            echo "Dockerfile was changed"
            docker run -i --rm "${IMAGE_NAME}:${IMAGE_TAG}" < Dockerfile            
          else
            echo "Dockerfile was not changed"
          fi
